# Kubernetes Deployment for TASA SatNet Pipeline
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasa-pipeline
  namespace: tasa-satnet
  labels:
    app: tasa-pipeline
    version: v1.0.0-alpha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasa-pipeline
  template:
    metadata:
      labels:
        app: tasa-pipeline
        version: v1.0.0-alpha
    spec:
      containers:
      - name: parser
        image: tasa-satnet-pipeline:latest
        imagePullPolicy: Never
        # Use default CMD from Dockerfile (healthcheck)
        # command: ["python"]
        # args: ["scripts/healthcheck.py"]
        envFrom:
        - configMapRef:
            name: tasa-pipeline-config
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        - name: reports-volume
          mountPath: /app/reports
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: tasa-data-pvc
      - name: reports-volume
        persistentVolumeClaim:
          claimName: tasa-reports-pvc
      restartPolicy: Always
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tasa-data-pvc
  namespace: tasa-satnet
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tasa-reports-pvc
  namespace: tasa-satnet
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
