# Kubernetes Job for running tests
apiVersion: batch/v1
kind: Job
metadata:
  name: tasa-test-job
  namespace: tasa-satnet
  labels:
    app: tasa-test
    component: testing
spec:
  template:
    metadata:
      labels:
        app: tasa-test
    spec:
      containers:
      - name: test-runner
        image: tasa-satnet-pipeline:latest
        imagePullPolicy: IfNotPresent
        command: ["pytest"]
        args:
          - "tests/"
          - "-v"
          - "--cov=scripts"
          - "--cov-report=term-missing"
          - "--cov-fail-under=90"
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      restartPolicy: Never
  backoffLimit: 1
